spring :
  application:
    name : highgrade

  config:
    import: classpath:secret.yml

  datasource:
    url : ENC(INrPuhGyCfy+ERR4xXal4PzuRt+3a7GsTQWinsNvMGuw4lgQ+c1LeZIbQCsbwbZ+EHk8UgQd7n0=)
    driver-class-name: org.postgresql.Driver
    username: ENC(DL7PVpAIFPCgvfL1GLNmR+oQPChZ7ktq)
    password: ENC(GvlMQ2FDsbE67r99KX3jM4T3k1wmeBji)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
