spring :
  application:
    name : highgrade

  datasource:
    url : ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 3600

cloud:
  aws:
    s3:
      bucket: spring-profile-image-bucket
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
