spring :
  application:
    name : highgrade

  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: byeongdoohan
    password: p@ssw0rd

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  header: Authorization
  secret : 73d92a19382d9482b51473abc5e74713767969462b8e2d1bc8b36a4a065ba8cd
  token-validity-in-seconds : 86400